let countriesMap = [
    ["Afghanistan", "Asia"],
    ["Albania", "Europe"],
    ["Algeria", "Africa"],
    ["American Samoa", "Oceania"],
    ["Andorra", "Europe"],
    ["Angola", "Africa"],
    ["Anguilla", "North America"],
    ["Antarctica", "Antarctica"],
    ["Antigua and Barbuda", "North America"],
    ["Argentina", "South America"],
    ["Armenia", "Asia"],
    ["Aruba", "North America"],
    ["Australia", "Oceania"],
    ["Austria", "Europe"],
    ["Azerbaijan", "Asia"],
    ["Bahamas", "North America"],
    ["Bahrain", "Asia"],
    ["Bangladesh", "Asia"],
    ["Barbados", "North America"],
    ["Belarus", "Europe"],
    ["Belgium", "Europe"],
    ["Belize", "North America"],
    ["Benin", "Africa"],
    ["Bermuda", "North America"],
    ["Bhutan", "Asia"],
    ["Bolivia", "South America"],
    ["Bosnia and Herzegovina", "Europe"],
    ["Botswana", "Africa"],
    ["Bouvet Island", "Antarctica"],
    ["Brazil", "South America"],
    ["British Indian Ocean Territory", "Africa"],
    ["Brunei", "Asia"],
    ["Bulgaria", "Europe"],
    ["Burkina Faso", "Africa"],
    ["Burundi", "Africa"],
    ["Cambodia", "Asia"],
    ["Cameroon", "Africa"],
    ["Canada", "North America"],
    ["Cape Verde", "Africa"],
    ["Cayman Islands", "North America"],
    ["Central African Republic", "Africa"],
    ["Chad", "Africa"],
    ["Chile", "South America"],
    ["China", "Asia"],
    ["Christmas Island", "Oceania"],
    ["Cocos (Keeling) Islands", "Oceania"],
    ["Colombia", "South America"],
    ["Comoros", "Africa"],
    ["Congo", "Africa"],
    ["Cook Islands", "Oceania"],
    ["Costa Rica", "North America"],
    ["Croatia", "Europe"],
    ["Cuba", "North America"],
    ["Cyprus", "Asia"],
    ["Czech Republic", "Europe"],
    ["Denmark", "Europe"],
    ["Djibouti", "Africa"],
    ["Dominica", "North America"],
    ["Dominican Republic", "North America"],
    ["East Timor", "Asia"],
    ["Ecuador", "South America"],
    ["Egypt", "Africa"],
    ["El Salvador", "North America"],
    ["England", "Europe"],
    ["Equatorial Guinea", "Africa"],
    ["Eritrea", "Africa"],
    ["Estonia", "Europe"],
    ["Ethiopia", "Africa"],
    ["Falkland Islands", "South America"],
    ["Faroe Islands", "Europe"],
    ["Fiji Islands", "Oceania"],
    ["Finland", "Europe"],
    ["France", "Europe"],
    ["French Guiana", "South America"],
    ["French Polynesia", "Oceania"],
    ["French Southern territories", "Antarctica"],
    ["Gabon", "Africa"],
    ["Gambia", "Africa"],
    ["Georgia", "Asia"],
    ["Germany", "Europe"],
    ["Ghana", "Africa"],
    ["Gibraltar", "Europe"],
    ["Greece", "Europe"],
    ["Greenland", "North America"],
    ["Grenada", "North America"],
    ["Guadeloupe", "North America"],
    ["Guam", "Oceania"],
    ["Guatemala", "North America"],
    ["Guinea", "Africa"],
    ["Guinea-Bissau", "Africa"],
    ["Guyana", "South America"],
    ["Haiti", "North America"],
    ["Heard Island and McDonald Islands", "Antarctica"],
    ["Holy See (Vatican City State)", "Europe"],
    ["Honduras", "North America"],
    ["Hong Kong", "Asia"],
    ["Hungary", "Europe"],
    ["Iceland", "Europe"],
    ["India", "Asia"],
    ["Indonesia", "Asia"],
    ["Iran", "Asia"],
    ["Iraq", "Asia"],
    ["Ireland", "Europe"],
    ["Israel", "Asia"],
    ["Italy", "Europe"],
    ["Ivory Coast", "Africa"],
    ["Jamaica", "North America"],
    ["Japan", "Asia"],
    ["Jordan", "Asia"],
    ["Kazakhstan", "Asia"],
    ["Kenya", "Africa"],
    ["Kiribati", "Oceania"],
    ["Kuwait", "Asia"],
    ["Kyrgyzstan", "Asia"],
    ["Laos", "Asia"],
    ["Latvia", "Europe"],
    ["Lebanon", "Asia"],
    ["Lesotho", "Africa"],
    ["Liberia", "Africa"],
    ["Libyan Arab Jamahiriya", "Africa"],
    ["Liechtenstein", "Europe"],
    ["Lithuania", "Europe"],
    ["Luxembourg", "Europe"],
    ["Macao", "Asia"],
    ["North Macedonia", "Europe"],
    ["Madagascar", "Africa"],
    ["Malawi", "Africa"],
    ["Malaysia", "Asia"],
    ["Maldives", "Asia"],
    ["Mali", "Africa"],
    ["Malta", "Europe"],
    ["Marshall Islands", "Oceania"],
    ["Martinique", "North America"],
    ["Mauritania", "Africa"],
    ["Mauritius", "Africa"],
    ["Mayotte", "Africa"],
    ["Mexico", "North America"],
    ["Micronesia, Federated States of", "Oceania"],
    ["Moldova", "Europe"],
    ["Monaco", "Europe"],
    ["Mongolia", "Asia"],
    ["Montenegro", "Europe"],
    ["Montserrat", "North America"],
    ["Morocco", "Africa"],
    ["Mozambique", "Africa"],
    ["Myanmar", "Asia"],
    ["Namibia", "Africa"],
    ["Nauru", "Oceania"],
    ["Nepal", "Asia"],
    ["Netherlands", "Europe"],
    ["Netherlands Antilles", "North America"],
    ["New Caledonia", "Oceania"],
    ["New Zealand", "Oceania"],
    ["Nicaragua", "North America"],
    ["Niger", "Africa"],
    ["Nigeria", "Africa"],
    ["Niue", "Oceania"],
    ["Norfolk Island", "Oceania"],
    ["North Korea", "Asia"],
    ["Northern Ireland", "Europe"],
    ["Northern Mariana Islands", "Oceania"],
    ["Norway", "Europe"],
    ["Oman", "Asia"],
    ["Pakistan", "Asia"],
    ["Palau", "Oceania"],
    ["Palestine", "Asia"],
    ["Panama", "North America"],
    ["Papua New Guinea", "Oceania"],
    ["Paraguay", "South America"],
    ["Peru", "South America"],
    ["Philippines", "Asia"],
    ["Pitcairn", "Oceania"],
    ["Poland", "Europe"],
    ["Portugal", "Europe"],
    ["Puerto Rico", "North America"],
    ["Qatar", "Asia"],
    ["Reunion", "Africa"],
    ["Romania", "Europe"],
    ["Russian Federation", "Europe"],
    ["Rwanda", "Africa"],
    ["Saint Helena", "Africa"],
    ["Saint Kitts and Nevis", "North America"],
    ["Saint Lucia", "North America"],
    ["Saint Pierre and Miquelon", "North America"],
    ["Saint Vincent and the Grenadines", "North America"],
    ["Samoa", "Oceania"],
    ["San Marino", "Europe"],
    ["Sao Tome and Principe", "Africa"],
    ["Saudi Arabia", "Asia"],
    ["Scotland", "Europe"],
    ["Senegal", "Africa"],
    ["Serbia", "Europe"],
    ["Seychelles", "Africa"],
    ["Sierra Leone", "Africa"],
    ["Singapore", "Asia"],
    ["Slovakia", "Europe"],
    ["Slovenia", "Europe"],
    ["Solomon Islands", "Oceania"],
    ["Somalia", "Africa"],
    ["South Africa", "Africa"],
    ["South Georgia and the South Sandwich Islands", "Antarctica"],
    ["South Korea", "Asia"],
    ["South Sudan", "Africa"],
    ["Spain", "Europe"],
    ["Sri Lanka", "Asia"],
    ["Sudan", "Africa"],
    ["Suriname", "South America"],
    ["Svalbard and Jan Mayen", "Europe"],
    ["Swaziland", "Africa"],
    ["Sweden", "Europe"],
    ["Switzerland", "Europe"],
    ["Syria", "Asia"],
    ["Tajikistan", "Asia"],
    ["Tanzania", "Africa"],
    ["Thailand", "Asia"],
    ["The Democratic Republic of Congo", "Africa"],
    ["Togo", "Africa"],
    ["Tokelau", "Oceania"],
    ["Tonga", "Oceania"],
    ["Trinidad and Tobago", "North America"],
    ["Tunisia", "Africa"],
    ["Turkey", "Asia"],
    ["Turkmenistan", "Asia"],
    ["Turks and Caicos Islands", "North America"],
    ["Tuvalu", "Oceania"],
    ["Uganda", "Africa"],
    ["Ukraine", "Europe"],
    ["United Arab Emirates", "Asia"],
    ["United Kingdom", "Europe"],
    ["United States", "North America"],
    ["United States Minor Outlying Islands", "Oceania"],
    ["Uruguay", "South America"],
    ["Uzbekistan", "Asia"],
    ["Vanuatu", "Oceania"],
    ["Venezuela", "South America"],
    ["Vietnam", "Asia"],
    ["Virgin Islands, British", "North America"],
    ["Virgin Islands, U.S.", "North America"],
    ["Wales", "Europe"],
    ["Wallis and Futuna", "Oceania"],
    ["Western Sahara", "Africa"],
    ["Yemen", "Asia"],
    ["Zambia", "Africa"],
    ["Zimbabwe", "Africa"],
];

/*
idPaises = {};
cnt = 0;
countriesMap.forEach((e) => {
    idPaises[e[0]] = cnt;
    cnt += 1;
});
console.log(idPaises);*/

let idPaises = {
    Afghanistan: 0,     
    Albania: 1,
    Algeria: 2,
    'American Samoa': 3,
    Andorra: 4,
    Angola: 5,
    Anguilla: 6,        
    Antarctica: 7,
    'Antigua and Barbuda': 8,
    Argentina: 9,
    Armenia: 10,
    Aruba: 11,
    Australia: 12,
    Austria: 13,
    Azerbaijan: 14,
    Bahamas: 15,
    Bahrain: 16,
    Bangladesh: 17,
    Barbados: 18,
    Belarus: 19,
    Belgium: 20,
    Belize: 21,
    Benin: 22,
    Bermuda: 23,
    Bhutan: 24,
    Bolivia: 25,
    'Bosnia and Herzegovina': 26,
    Botswana: 27,
    'Bouvet Island': 28,
    Brazil: 29,
    'British Indian Ocean Territory': 30,
    Brunei: 31,
    Bulgaria: 32,
    'Burkina Faso': 33,
    Burundi: 34,
    Cambodia: 35,
    Cameroon: 36,
    Canada: 37,
    'Cape Verde': 38,
    'Cayman Islands': 39,
    'Central African Republic': 40,
    Chad: 41,
    Chile: 42,
    China: 43,
    'Christmas Island': 44,
    'Cocos (Keeling) Islands': 45,
    Colombia: 46,
    Comoros: 47,
    Congo: 48,
    'Cook Islands': 49,
    'Costa Rica': 50,
    Croatia: 51,
    Cuba: 52,
    Cyprus: 53,
    'Czech Republic': 54,
    Denmark: 55,
    Djibouti: 56,
    Dominica: 57,
    'Dominican Republic': 58,
    'East Timor': 59,
    Ecuador: 60,
    Egypt: 61,
    'El Salvador': 62,
    England: 63,
    'Equatorial Guinea': 64,
    Eritrea: 65,
    Estonia: 66,
    Ethiopia: 67,
    'Falkland Islands': 68,
    'Faroe Islands': 69,
    'Fiji Islands': 70,
    Finland: 71,
    France: 72,
    'French Guiana': 73,
    'French Polynesia': 74,
    'French Southern territories': 75,
    Gabon: 76,
    Gambia: 77,
    Georgia: 78,
    Germany: 79,
    Ghana: 80,
    Gibraltar: 81,
    Greece: 82,
    Greenland: 83,
    Grenada: 84,
    Guadeloupe: 85,
    Guam: 86,
    Guatemala: 87,
    Guinea: 88,
    'Guinea-Bissau': 89,
    Guyana: 90,
    Haiti: 91,
    'Heard Island and McDonald Islands': 92,
    'Holy See (Vatican City State)': 93,
    Honduras: 94,
    'Hong Kong': 95,
    Hungary: 96,
    Iceland: 97,
    India: 98,
    Indonesia: 99,
    Iran: 100,
    Iraq: 101,
    Ireland: 102,
    Israel: 103,
    Italy: 104,
    'Ivory Coast': 105,
    Jamaica: 106,
    Japan: 107,
    Jordan: 108,
    Kazakhstan: 109,
    Kenya: 110,
    Kiribati: 111,
    Kuwait: 112,
    Kyrgyzstan: 113,
    Laos: 114,
    Latvia: 115,
    Lebanon: 116,
    Lesotho: 117,
    Liberia: 118,
    'Libyan Arab Jamahiriya': 119,
    Liechtenstein: 120,
    Lithuania: 121,
    Luxembourg: 122,
    Macao: 123,
    'North Macedonia': 124,
    Madagascar: 125,
    Malawi: 126,
    Malaysia: 127,
    Maldives: 128,
    Mali: 129,
    Malta: 130,
    'Marshall Islands': 131,
    Martinique: 132,
    Mauritania: 133,
    Mauritius: 134,
    Mayotte: 135,
    Mexico: 136,
    'Micronesia, Federated States of': 137,
    Moldova: 138,
    Monaco: 139,
    Mongolia: 140,
    Montenegro: 141,
    Montserrat: 142,
    Morocco: 143,
    Mozambique: 144,
    Myanmar: 145,
    Namibia: 146,
    Nauru: 147,
    Nepal: 148,
    Netherlands: 149,
    'Netherlands Antilles': 150,
    'New Caledonia': 151,
    'New Zealand': 152,
    Nicaragua: 153,
    Niger: 154,
    Nigeria: 155,
    Niue: 156,
    'Norfolk Island': 157,
    'North Korea': 158,
    'Northern Ireland': 159,
    'Northern Mariana Islands': 160,
    Norway: 161,
    Oman: 162,
    Pakistan: 163,
    Palau: 164,
    Palestine: 165,
    Panama: 166,
    'Papua New Guinea': 167,
    Paraguay: 168,
    Peru: 169,
    Philippines: 170,
    Pitcairn: 171,
    Poland: 172,
    Portugal: 173,
    'Puerto Rico': 174,
    Qatar: 175,
    Reunion: 176,
    Romania: 177,
    'Russian Federation': 178,
    Rwanda: 179,
    'Saint Helena': 180,
    'Saint Kitts and Nevis': 181,
    'Saint Lucia': 182,
    'Saint Pierre and Miquelon': 183,
    'Saint Vincent and the Grenadines': 184,
    Samoa: 185,
    'San Marino': 186,
    'Sao Tome and Principe': 187,
    'Saudi Arabia': 188,
    Scotland: 189,
    Senegal: 190,
    Serbia: 191,
    Seychelles: 192,
    'Sierra Leone': 193,
    Singapore: 194,
    Slovakia: 195,
    Slovenia: 196,
    'Solomon Islands': 197,
    Somalia: 198,
    'South Africa': 199,
    'South Georgia and the South Sandwich Islands': 200,
    'South Korea': 201,
    'South Sudan': 202,
    Spain: 203,
    'Sri Lanka': 204,
    Sudan: 205,
    Suriname: 206,
    'Svalbard and Jan Mayen': 207,
    Swaziland: 208,
    Sweden: 209,
    Switzerland: 210,
    Syria: 211,
    Tajikistan: 212,
    Tanzania: 213,
    Thailand: 214,
    'The Democratic Republic of Congo': 215,
    Togo: 216,
    Tokelau: 217,
    Tonga: 218,
    'Trinidad and Tobago': 219,
    Tunisia: 220,
    Turkey: 221,
    Turkmenistan: 222,
    'Turks and Caicos Islands': 223,
    Tuvalu: 224,
    Uganda: 225,
    Ukraine: 226,
    'United Arab Emirates': 227,
    'United Kingdom': 228,
    'United States': 229,
    'United States Minor Outlying Islands': 230,
    Uruguay: 231,
    Uzbekistan: 232,
    Vanuatu: 233,
    Venezuela: 234,
    Vietnam: 235,
    'Virgin Islands, U.S.': 237,
    Wales: 238,
    'Wallis and Futuna': 239,
    'Western Sahara': 240,
    Yemen: 241,
    Zambia: 242,
    Zimbabwe: 243
  }